### PR TITLE
Add QQ, UU, QU indexing to Fourier-diagonal EB covariances

### PR DESCRIPTION
**Pull request by cailmdaley**
This PR adds functionality to rotate EB covariances into QQ, UU, and QU covariances (if the EB covariance is diagonal in Fourier space.)

I think this needs to be implemented separately for FlatS2s and FlatS02s?

### CODE REVIEW

**Comment by marius311** [comment]
Awesome, thanks! Couple of minor comments:

* Can you use `@match` and also just do `getindex` instead of `Base.getindex` so it basically matches the style of the function right above it? (at some point I'll probably switch the entire codebase to the `Base.getindex` style which is probably better, but for now I just want to keep it homogenous)

* Can you add `:UQ` for completeness?

* Can you add a test? I'm thinking something along the lines of:

    ```julia
    C :: Diagonal{<:FlatEBFourier} = ...
    f :: FlatS2 = ...

    @test C*f ≈ FlatQUFourier(C[:QQ]*f[:Q]+C[:QU]*f[:U], C[:UU]*f[:U]+C[:UQ]*f[:Q])
    ```

For the `ParamDependentOp`, I don't think that'll quite work since you haven't changed the `recompute_function`, so eg `C[:QQ](θ)` would actually return a `Diagonal{<:FlatEBFourier}` still. I think its probably clearest to follow the convention with these `ParamDependentOp`s which is that as soon as you do anything to them, they lose their param-dependence-ness and get evaluated at the fiducial parameters. This is basically what https://github.com/marius311/CMBLensing.jl/blob/587efdf70a8816109a4ea65c8117a9719e2ff629/src/specialops.jl#L229-L231 does. Maybe right below there, add something like `getindex(L::ParamDependentOp, x) = getindex(L.op, x)`, so that `C[:QQ]` if `C::ParamDependentOp` will just evaluate it at fiducial parameters and then return the `:QQ` block.

**Comment by marius311** [comment]
For `C::FlatS02`, since `C[:P]` already returns a `Diagonal{<:FlatEBFourier}` with the P block, I think it can be a one-line
```julia
(:QQ || :UU || :QU || :UQ) => getindex(L[:P], k)
```
added to https://github.com/marius311/CMBLensing.jl/blob/587efdf70a8816109a4ea65c8117a9719e2ff629/src/flat_s0s2.jl#L112-L117

Also, I realize now there's an inconsistency since its `C[:E]` but its `C[:QQ]`. I think your convention is clearer though, I will try to make it `C[:EE]` in a followup (after I think if that breaks anything badly, don't think so...)

**Comment by cailmdaley** [comment]
Thanks Marius, everything now works out as you suggested. It basically wrote itself!

I'm now also thinking about adding `:TQ` and `:TU` indexing, and maybe even `:QE, :QB, :UE, :UB` (I'm wondering if you could use a GP to delens, filter, and do the QU -> EB transform all in one map-space step..). If this seems reasonable I can take a stab at it.

**Comment by marius311** [comment]
Thanks again! I agree the other stuff would make sense to have too, would be happy to take.

**Pull request merged**
