### PR TITLE
CUDA 3 support, drop OptimKit, add diagonal Hessian updates in MAP_joint

### PR DESCRIPTION
**Pull request by marius311**
Aggregate of a bunch of things: 

* Drop OptimKit and LBFGS entirely. The LBFGS just wasn't significantly better, sometimes worse actually. Additionally, https://github.com/Jutho/OptimKit.jl/issues/11 was just proving to be too annoying. Instead, MAP_joint now does some simple isotropized diagonal-only updates to the Hessian after a pre-determined burnin, which in practice I find works much better than LBFGS ever did. 

* Adds a new function `get_max_lensing_step` that prevents trying to take a ϕ step so large that the subsequent magnification matrix is singular which would then cause LenseFlow to error. 

* Rewrites `MAP_marg` to only depend on `lnP`, so if that's changed, its self-consistently refelected in the `MAP_marg` result .

* Adds CUDA 3 support, drops CUDA 2 support. 

* Drops julia 1.5 support.

### CODE REVIEW

**Comment by marius311** [comment]
@kimmywu I'm ready to merge this but can you check it doesn't break any of your marginal MAP stuff first and approve it when done?

Fyi, on NERSC, I'm now running with `module load cuda/11.3.0` and `export JULIA_CUDA_MEMORY_POOL=binned`

I double checked with https://github.com/marius311/marginal_MAP_example/blob/master/marginal_MAP_example.ipynb and it runs fine (and MAP_marg is almost ~2x faster). I also updated the MAP_marg code to only depend on `lnP`, so it thats changed the MAP_marg code will be self-consistent, as well as combining the old `δlnP_δϕ` into `MAP_marg` for simplicity.

**Comment by kimmywu** [comment]
Ran a test on one of my setups and the results look sensible. Super like the fact that dlnP_dϕ for marg_MAP is merged with lnP and the flexibility that this brings!

**Review by kimmywu — APPROVED** [review]
Ran a test on one of my setups and the results look sensible. Super like the fact that dlnP_dϕ for marg_MAP is merged with lnP and the flexibility that this brings! 

Note the NERSC gpu node I tested this on didn't have `cuda/11.3.0`. And I was running on cuda/11.0.0, and got a warning. But everything else ran fine.

**Comment by marius311** [comment]
Awesome, thank you for checking quickly. Will merge shortly.

**Pull request merged**
